services:
  cms:
    image: imgreg.chemserv.scc.kit.edu/chemotion-web/cms:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database:/opt/app/database
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - nginx-proxy
networks:
  nginx-proxy:
    external: true